#!/usr/bin/env bash
for f1 in *1_001.fastq.gz
do
  f0=${f1%%1_001.fastq.gz}
  f2=$f0"2_001.fastq.gz"
  /home/ld15/fastp -i $f1 -I $f2 -o "trimmed-$f1" -O "trimmed-$f2" -h "$f0.html" -j "$f0.json"
done